### ISSUE TITLE
href nodes hidden by header

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/PkgPage.jl#38] opened 2020-10-05 13:34 UTC
e.g. go to https://kristofferc.github.io/LazilyInitializedFields.jl/#use_a_reft_field you see that the header containing the href are hidden by the header.

**Comment by tlienart** [comment] 2020-10-05 13:37
A bit similar to #37 in that the base one has the proper behaviour (see eg: https://tlienart.github.io/PkgPage.jl/#getting_started)

But it's just a CSS class if the headers are done manually: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

**Comment by fredrikekre** [comment] 2020-10-05 13:38
Okay, sorry for spamming you instead of @KristofferC with issues :D

**Comment by KristofferC** [comment] 2020-10-05 13:40
Bruh, I didn't change almost anything in the config!

**Comment by tlienart** [comment] 2020-10-05 13:43
haha no worries, ok so here the issue is with sub-headers; I would suggest not making them links that will be the easiest fix (and given the page is quite short I think that's not really an issue). For this just replace the `### ... ` by `~~~<h3>TITLE</h3>~~~`

It's a bit hacky but it will also solve the blue look and might just look better. Also maybe add me as a contributor to the repo and I can do some light CSS touches to help out

**Comment by KristofferC** [comment] 2020-10-05 13:52
I think the problem was actually a missing `\end{:section}` in the end of the document.

**Comment by tlienart** [comment] 2020-10-05 13:56
☝️ for the footer thing yes, for the headers that when you click on them get hidden by the navbar, I think it's likely still an issue (but if it magically also fixed itself then great :joy:) also in a near future these "begin-end" things will be better supported by Franklin and it will tell you when you forget stuff.

**Comment by KristofferC** [comment] 2020-10-05 13:58
I changed to `<h4>` and seems to work great now. Thanks.

**Comment by KristofferC** [comment] 2020-10-05 14:42
Oh, but code quoting doesn't work inside `<h4>`.

**Comment by tlienart** [comment] 2020-10-05 15:01
can you try using <code> ... <code> in the title.?

**Comment by tlienart** [comment] 2020-10-10 17:23
Seems this is all fixed in https://kristofferc.github.io/LazilyInitializedFields.jl/#other_methods , closing (feel free to reopen this or open another issue if there's still something to fix I might have missed)

**Closed by tlienart** 2020-10-10 17:23 UTC
